import uuid
from django.db import models

class Client(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization_name = models.CharField(max_length=255)
    contact_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=50)
    country = models.CharField(max_length=100)
    domain_tags = models.JSONField(default=list)
    engagement_scope = models.JSONField(default=list)
    project_stage = models.CharField(max_length=100)
    budget_range = models.CharField(max_length=100)
    engagement_type = models.CharField(max_length=50, choices=[('one_time', 'One Time'), ('retainer', 'Retainer')])
    assigned_consultant_id = models.UUIDField(null=True, blank=True)
    assignment_status = models.CharField(max_length=50, choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed')], default='unassigned')
    onboarded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.organization_name} ({self.contact_name})"

class Consultant(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=50)
    domain_expertise = models.JSONField(default=list)
    bio = models.TextField()
    years_experience = models.IntegerField()
    linkedin_url = models.URLField(null=True, blank=True)
    availability_status = models.CharField(max_length=50, choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave')], default='available')
    kyc_status = models.CharField(max_length=50, choices=[('pending', 'Pending'), ('partial', 'Partial'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='pending')
    active_client_count = models.IntegerField(default=0)
    rating = models.FloatField(default=0.0)
    onboarded_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class KYCDocument(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    consultant = models.ForeignKey(Consultant, on_delete=models.CASCADE, related_name='kyc_documents')
    document_type = models.CharField(max_length=50, choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('bank_account', 'Bank Account'), ('background_check', 'Background Check'), ('photo', 'Photo'), ('agreement', 'Agreement')])
    file_url = models.URLField(max_length=500)
    submitted_at = models.DateTimeField(auto_now_add=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)
    reviewed_by = models.UUIDField(null=True, blank=True)
    status = models.CharField(max_length=50, choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted')
    rejection_reason = models.TextField(null=True, blank=True)

class Engagement(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='engagements')
    consultant = models.ForeignKey(Consultant, null=True, blank=True, on_delete=models.CASCADE, related_name='engagements')
    scope = models.JSONField(default=list)
    stage = models.CharField(max_length=100)
    status = models.CharField(max_length=50, choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active')
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Milestone(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    engagement = models.ForeignKey(Engagement, on_delete=models.CASCADE, related_name='milestones')
    name = models.CharField(max_length=255)
    due_date = models.DateField()
    status = models.CharField(max_length=50, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not_started')
    owner = models.CharField(max_length=50, choices=[('client', 'Client'), ('consultant', 'Consultant'), ('both', 'Both')])
    notes = models.TextField(null=True, blank=True)
    attachment_url = models.URLField(max_length=500, null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

class Lead(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    submitted_by = models.ForeignKey(Consultant, on_delete=models.CASCADE, related_name='leads')
    organization_name = models.CharField(max_length=255)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=50, null=True, blank=True)
    domain = models.CharField(max_length=100)
    estimated_value = models.DecimalField(max_digits=12, decimal_places=2)
    engagement_type = models.CharField(max_length=50)
    description = models.TextField()
    source = models.CharField(max_length=100)
    pipeline_stage = models.CharField(max_length=50, choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('contacted', 'Contacted'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='submitted')
    referral_bonus_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    referral_bonus_status = models.CharField(max_length=50, choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='not_applicable')
    submitted_at = models.DateTimeField(auto_now_add=True)

class Payout(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    consultant = models.ForeignKey(Consultant, on_delete=models.CASCADE, related_name='payouts')
    period_month = models.IntegerField()
    period_year = models.IntegerField()
    gross_earnings = models.DecimalField(max_digits=12, decimal_places=2)
    platform_fee_pct = models.DecimalField(max_digits=5, decimal_places=4)
    platform_fee_amount = models.DecimalField(max_digits=10, decimal_places=2)
    net_payout = models.DecimalField(max_digits=12, decimal_places=2)
    referral_bonus = models.DecimalField(max_digits=10, decimal_places=2)
    total_due = models.DecimalField(max_digits=12, decimal_places=2)
    status = models.CharField(max_length=50, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending')
    approved_by = models.UUIDField(null=True, blank=True)
    approved_at = models.DateTimeField(null=True, blank=True)
    paid_at = models.DateTimeField(null=True, blank=True)

class EngagementQuote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    engagement = models.ForeignKey(Engagement, on_delete=models.CASCADE, related_name='quotes')
    ai_recommended_price = models.DecimalField(max_digits=12, decimal_places=2)
    ai_price_range_low = models.DecimalField(max_digits=12, decimal_places=2)
    ai_price_range_high = models.DecimalField(max_digits=12, decimal_places=2)
    ai_rationale = models.TextField()
    ai_confidence_score = models.FloatField()
    ai_estimated_weeks = models.IntegerField()
    admin_override_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    admin_override_note = models.TextField(null=True, blank=True)
    final_price = models.DecimalField(max_digits=12, decimal_places=2)
    status = models.CharField(max_length=50, choices=[('pending_admin', 'Pending Admin'), ('sent_to_client', 'Sent to Client'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted')], default='pending_admin')
    created_at = models.DateTimeField(auto_now_add=True)
    sent_at = models.DateTimeField(null=True, blank=True)

class ClientPayment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    engagement = models.ForeignKey(Engagement, on_delete=models.CASCADE, related_name='payments')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='payments')
    quote = models.ForeignKey(EngagementQuote, on_delete=models.CASCADE, related_name='payments')
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=10, choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR')])
    gateway = models.CharField(max_length=50)
    gateway_payment_id = models.CharField(max_length=255)
    platform_fee_pct = models.DecimalField(max_digits=5, decimal_places=4)
    platform_fee_amount = models.DecimalField(max_digits=10, decimal_places=2)
    consultant_payout_amount = models.DecimalField(max_digits=12, decimal_places=2)
    status = models.CharField(max_length=50, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending')
    paid_at = models.DateTimeField(null=True, blank=True)
    refunded_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

class ConsultantSubscription(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    consultant = models.ForeignKey(Consultant, on_delete=models.CASCADE, related_name='subscriptions')
    plan = models.CharField(max_length=50, choices=[('starter', 'Starter'), ('professional', 'Professional'), ('growth', 'Growth')])
    billing_cycle = models.CharField(max_length=50, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')])
    price_inr = models.DecimalField(max_digits=10, decimal_places=2)
    price_usd = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=50, choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')])
    gateway = models.CharField(max_length=50)
    gateway_subscription_id = models.CharField(max_length=255)
    trial_ends_at = models.DateTimeField(null=True, blank=True)
    current_period_start = models.DateTimeField()
    current_period_end = models.DateTimeField()
    cancelled_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
